# 배포가 실행되면 ec2에 설치된 CodeDeploy agent에서 해당 파일을보고, 받아온 프로젝트를 어디에 저장할지, 무엇을 실행할지를 정함.

version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/bullet
permissions:
  - object: /home/ubuntu/bullet
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
